services:
  - type: web
    name: testapp-pyne
    plan: standard
    repo: https://github.com/calcom/docker.git
    dockerfilePath: ./Dockerfile.render
    env: docker
    region: frankfurt
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: testapp-pyne-postgres
          property: connectionString
      - key: CALENDSO_ENCRYPTION_KEY
        value: secret
      - key: NEXTAUTH_SECRET
        value: secret
      - key: CRON_API_KEY
        value: 0cc0e6c35519bba620c9360cfe3e68d0
databases:
  - name: testapp-pyne-postgres
    plan: starter
    region: frankfurt
